### ISSUE TITLE
EPIPE Error on Python execution

### ISSUE THREAD

**Issue by santisantosh** [vibhor1997a/compile-run#3]
var compile_run = require('compile-run');
compile_run.runPython('C:/Users/<<>>/AppData/Local/Programs/Python/Python36-32/p2.py',function (stdout, stderr, err) {
    if(!err){
        console.log(stdout);
        console.log(stderr);
    }
    else{
        console.log(err);
    }
});

this throws me error as below

**Error: write EPIPE**
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:710:26)
    at Socket._write (net.js:729:8)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at Socket.Writable.write (_stream_writable.js:246:11)
    at Socket.write (net.js:656:40)

**Comment by suryatmodulus** [comment]
try using compiler_run.runFile  instead of compile_run.runPython
